from . import user_model
from . import staff_model
from . import manager_model
from . import payroll_model
from . import teacher_model
from . import parent_model
from . import student_model
from . import studentparent_model
from . import subject_model
from . import score_model
from . import tuition_model
from . import studentclass_model
from . import class_model
from . import enrollment_model
from . import attendance_model
from . import evaluation_model
from . import schedule_model
from . import teacherpoint_model
from . import notification_model
