from . import user_crud
from . import user_role_crud
from . import staff_crud
from . import manager_crud
from . import payroll_crud
from . import teacher_crud
from . import parent_crud
from . import student_crud
from . import student_parent_crud
from . import subject_crud
from . import score_crud
from . import tuition_crud
from . import student_class_crud
from . import class_crud
from . import attendance_crud
from . import evaluation_crud
from . import schedule_crud
from . import teacherpoint_crud
from . import notification_crud
